# Generated by Django 5.2.4 on 2025-07-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('basic_salary', models.IntegerField()),
                ('allowance', models.IntegerField()),
                ('deductions', models.IntegerField()),
            ],
        ),
    ]
